# Generated by Django 5.0.6 on 2024-06-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_usuariostandard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioStandard',
        ),
    ]
