# Generated by Django 5.0.6 on 2024-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cliente_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='cliente_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cliente_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
