# Generated by Django 5.0.6 on 2024-06-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_carritoitem_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cilindraje',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='potencia_maxima',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_motor',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='torque_maximo',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
