# Generated by Django 5.0.6 on 2024-06-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_producto_cilindraje_remove_producto_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
